server:
  port: 8190

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
      url: jdbc:h2:file:~/test
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialec
    h2:
      console:
        enabled: true
        path: /h2
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      fetchRegistry: false